const discord = require('discord.js')
module.exports = {
    name: "poll",
    info: 'generate a poll to vote',
    guildOnly: true,
    args: true,
    usage: '<things to vote>',
    async execute(message, args) {
        let idk = args.slice(0).join(" ")
        let embed = new discord.RichEmbed()
            .setColor('GREEN')
            .setDescription(idk)
            .setFooter(`Generated by: ${message.author.username}`, message.author.avatarURL)
        message.channel.send(embed).then(msg => {
            msg.react('412529951238258688').then(() => {
                msg.react('412529964945113100')
            })
        })
    }
}